### ISSUE TITLE
Thanks for update. Tried to launch the latest version but got this error:

### ISSUE THREAD

**Issue by JohnClaw** [fszontagh/sd.cpp.gui.wx#19]
![{6A4A8A4E-06BE-47ED-A57B-E9BC43EA0001}](https://github.com/user-attachments/assets/7ee85cca-e4b2-416a-a89b-8884eecc1e88)

Can it be fixed somehow?

**Comment by fszontagh** [comment]
@JohnClaw Oh. There is no hiplas(rocm) build in the workflow yet.

If you can change the backend, you can force it with startup arguments, for example: 
sd_ui.exe -cuda
or 
sd_ui.exe -avx 

There is currently avx, avx2, avx512 and cuda builds available only.

I will update the build workflow today, but before I will manually build a rocm for testing.

**Comment by JohnClaw** [comment]
Thanks for answer. Now app runs without that error message.
