### ISSUE TITLE
Could you compile an exe for Windows, please?

### ISSUE THREAD

**Issue by JohnClaw** [fszontagh/sd.cpp.gui.wx#2]
...

**Comment by fszontagh** [comment]
[Made some packages for Win. ](https://fsociety.hu/sd.cpp.gui.wx/releases/)
Please test it out respect to the versions. 
If you find some bug, please report it in a new ticket.

**Comment by OcelotMadness** [comment]
Would it be possible to get a windows Arm64 version?

**Comment by fszontagh** [comment]
Yeah, maybe it is possible. But i don't own such device which running with Windows arm64, so i can't test is. 
Maybe if you open a new issue for it, somebody can modify the git workflow to build and release Win arm64 binaries
