### ISSUE TITLE
Appimage missing library errors

### ISSUE THREAD

**Issue by einhander** [fszontagh/sd.cpp.gui.wx#25]
Please add libexiv2.27 and jpeg8 to appimage, on debian testing where libexiv2.28.

**Comment by fszontagh** [comment]
I tried to make an AppImage which contains more libraries. But it's size more than 2GB, which is unreleasable. 
So, maybe it is easier to compile from source.
And there is no debian distributions here at the github runners, so i can't release debian packages.

**Comment by einhander** [comment]
> i added the libexiv2, libjpeg, libpng shared libs

That's strange, because both appimage versions can't find these libs.

**Comment by fszontagh** [comment]
> > i added the libexiv2, libjpeg, libpng shared libs
> 
> That's strange, because both appimage versions can't find these libs.

No, sorry, not in the current releases. On the next release will be available.

**Comment by einhander** [comment]
>On the next release will be available.

I'm looking forward to it. 
I'll reopen this issue if problem persists.
