### ISSUE TITLE
`libstable-diffusion_vulkan.so` missing from `.AppImage` ?

### ISSUE THREAD

**Issue by SuperUserNameMan** [fszontagh/sd.cpp.gui.wx#26]
Hello and nice work on this GUI !

I was testing the fresh new 0.2.2 AppImage version on my Linux Mint.

I launched it using `-vulkan` argument, but it does not work because the `appImage` does not contain the `libstable-diffusion_vulkan.so`. 

Vulkan is the only GPU acceleration available on my Laptop, so I was wondering if you could enable vulkan support for the next release ?

**Comment by fszontagh** [comment]
Hello @SuperUserNameMan !

Sorry, but there is no pre built binaries for the vulkan backend yet.

[Here](https://github.com/fszontagh/sd.cpp.gui.wx/wiki/Installation-Guide#summary-of-shared-libraries) is the list of the currently supported backends. 


But you can try to build the vulkan backend locally:
1. clone the sd.cpp repo, switch to the [master-9578fdc](https://github.com/leejet/stable-diffusion.cpp/releases/tag/master-9578fdc) tag, 
2. follow the [build docs](https://github.com/leejet/stable-diffusion.cpp#using-vulkan) to build a shared library
3. rename the stable-diffusion.so to stable-diffusion_vulkan.so, then place into the /usr/lib system folder


But as i know, the master-9578fdc sd.cpp have some trouble with the vulkan backend, but there is some PR which will fix it.

**Comment by fszontagh** [comment]
> Which troubles are you referring to ?

As the same what you [linked](https://github.com/leejet/stable-diffusion.cpp/issues/439)

> i just compiled the lib with a manually updated version of ggml.

Nice catch. I have no device for vulkan, so i can't test it. 
Because the binaries built here in the github workflow, i can't change the ggml version.
