### ISSUE TITLE
Sd.cpp.gui.wx uses only 57% of CPU threads

### ISSUE THREAD

**Issue by JohnClaw** [fszontagh/sd.cpp.gui.wx#9]
First of all, i want to thank you for adding ability to choose amount of cpu cores used for image generation. Unfortunately, this option doesn't work as it supposed to. While compiled cli version of sd.cpp uses 99% of cpu threads, your gui uses only 57% (I used AMD Adrenaline overlay to monitor cpu usage). Could it be fixed somehow, please?

**Comment by fszontagh** [comment]
Wich CPU have you?

**Comment by JohnClaw** [comment]
> Wich CPU have you?
> 
> Bytheway, it's a wrong idea to use all threads on your CPU. I read it somewhere earlier, only good idea to use only the cores and not the threads.

My laptop's cpu is Ryzen 7 4700u, 8 cores, 8 threads. When i run cli version of sd.cpp, it always uses all 8 threads (99% cpu usage in AMD Adrenaline overlay) and generates images faster than sd.cpp.gui.wx.

**Comment by fszontagh** [comment]
Can you post your config file's content please? 
You can find here: _C:\Users\<username>\AppData\Roaming\sd.ui.config.ini_

**Comment by JohnClaw** [comment]
> Can you post your config file's content please?

keep_model_in_memory=1
save_all_image=1
n_threads=8
[paths]
lora=C:\\Users\\John\\AppData\\Roaming\\sd.ui\\sd_ui_data\\lora
model=C:\\Users\\John\\Downloads
vae=C:\\Users\\John\\AppData\\Roaming\\sd.ui\\sd_ui_data\\vae
embedding=C:\\Users\\John\\AppData\\Roaming\\sd.ui\\sd_ui_data\\embedding
presets=C:\\Users\\John\\AppData\\Roaming\\sd.ui\\sd_ui_data\\presets
taesd=C:\\Users\\John\\AppData\\Roaming\\sd.ui\\sd_ui_data\\taesd

**Comment by fszontagh** [comment]
Can you please rewrite the "Number of the CPU cores" option in the "Settings -> Diffusion tab"? Eg. to 2, and start a job? 

Please check out what's happening then. You can stop the diffusion if you close the main window, thats will abort the process. For testing please only diffuse with small resolution with minimal sampling steps. 

And please try-out what's happening, when you set the same setting to 16. 

Whats parameters are you use with sd.exe?

**Comment by JohnClaw** [comment]
> Whats parameters are you use with sd.exe?

sd.exe -m LCM_Dreamshaper_v7-f16.gguf -t 8 --steps 4 --height 512 --width 512 --seed -1 -p "a room" -o room4.png --cfg-scale 1.0 --sampling-method lcm

**Comment by JohnClaw** [comment]
> Can you please rewrite the "Number of the CPU cores" option in the "Settings -> Diffusion tab"? Eg. to 2, and start a job?

> And please try-out what's happening, when you set the same setting to 16.

In both cases CPU usage is 57%. It takes 151 s to make a 512x512 image. When CPU usage is 99% (cli sd.exe), it takes only 91 s.
